# Generated by Django 6.0.2 on 2026-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['group_number', 'course'], name='accounts_us_group_n_14b5b2_idx'),
        ),
    ]
