# Generated by Django 6.0.2 on 2026-03-07 06:10

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['service'], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
