# Generated by Django 6.0.2 on 2026-03-07 07:25

from django.db import migrations

import apps.security.models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_account_options_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=apps.security.models.EncryptedField(),
        ),
    ]
