# Generated by Django 6.0.2 on 2026-03-07 06:39

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='Connection'),
        migrations.DeleteModel(name='ConnectionCategory'),
    ]
