# Generated by Django 6.0.2 on 2026-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('important', 'Важная дата'), ('session', 'Сессия'), ('holiday', 'Каникулы'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
