# Generated by Django 6.1.1 on 2026-09-24 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'date'], name='calendar_ap_user_id_dd728f_idx'),
        ),
    ]
